// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNn20_HZRhv8UZsslmFWHVaGQh-d7LXQ',
    appId: '1:105859233683:web:ce992b9d7ee934d8ac9a66',
    messagingSenderId: '105859233683',
    projectId: 'connectivity-firebase-2b709',
    authDomain: 'connectivity-firebase-2b709.firebaseapp.com',
    storageBucket: 'connectivity-firebase-2b709.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMu8DaIMOCpXmgp4n3ygdcD-qFOdoqVz8',
    appId: '1:105859233683:android:cfffef6788dce6bbac9a66',
    messagingSenderId: '105859233683',
    projectId: 'connectivity-firebase-2b709',
    storageBucket: 'connectivity-firebase-2b709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMkcdSrl0_pgDueTj1677UmzJcHrpUR3o',
    appId: '1:105859233683:ios:632aa805ba882907ac9a66',
    messagingSenderId: '105859233683',
    projectId: 'connectivity-firebase-2b709',
    storageBucket: 'connectivity-firebase-2b709.firebasestorage.app',
    iosClientId: '105859233683-gc276q3sost34706km3osasvanr0c98b.apps.googleusercontent.com',
    iosBundleId: 'com.example.crackerShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMkcdSrl0_pgDueTj1677UmzJcHrpUR3o',
    appId: '1:105859233683:ios:632aa805ba882907ac9a66',
    messagingSenderId: '105859233683',
    projectId: 'connectivity-firebase-2b709',
    storageBucket: 'connectivity-firebase-2b709.firebasestorage.app',
    iosClientId: '105859233683-gc276q3sost34706km3osasvanr0c98b.apps.googleusercontent.com',
    iosBundleId: 'com.example.crackerShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZNn20_HZRhv8UZsslmFWHVaGQh-d7LXQ',
    appId: '1:105859233683:web:164551685ade3ee5ac9a66',
    messagingSenderId: '105859233683',
    projectId: 'connectivity-firebase-2b709',
    authDomain: 'connectivity-firebase-2b709.firebaseapp.com',
    storageBucket: 'connectivity-firebase-2b709.firebasestorage.app',
  );

}